### ISSUE TITLE
'MPU9250' does not name a type

### ISSUE THREAD

**Issue by bvandenberg** [Xinyuan-LilyGO/LilyGo-T-Wristband#12]
When uploading the example program I get the following error. How to resolve? Thank you!
`'MPU9250' does not name a type`

![image](https://user-images.githubusercontent.com/5312938/76400217-3a1a7e80-6380-11ea-9764-189bc115c2ed.png)

**Comment by cpetito** [comment]
You need to have these other files in the sketch folder:

![image](https://user-images.githubusercontent.com/16942717/76477112-b9d53700-63da-11ea-925c-ed9573898d33.png)

**Comment by lewisxhe** [comment]
As @cpetito said, you did not check the README carefully

**Comment by UPocek** [comment]
Try prefixing class declaration with bfs::

```
bfs::Mpu6500 mpu6500(&SPI, 2);
```

this works for me
