### ISSUE TITLE
ST7735_x not delared in this scope

### ISSUE THREAD

**Issue by Korvian** [Xinyuan-LilyGO/LilyGO-T-Wristband#13]
I'm using Arduino IDE and when compiling I get the following errors:
'ST7735_SLPIN' was not declared in this scope
'ST7735_DISPOFF' was not declared in this scope

The related lines are 503 and 504 from LilyGO-T-Wristband.ino
tft.writecommand(ST7735_SLPIN);
tft.writecommand(ST7735_DISPOFF);

I've followed the Readme.md as best I can but it is not clear for me.

**Comment by codebombi** [comment]
Did you manage to fix it?
