### ISSUE TITLE
TECH SUPPORT IS NOT RESPONDING

### ISSUE THREAD

**Issue by boogie** [Xinyuan-LilyGO/LilyGo-T-Wristband#15]
Wrote to them about the battery issues of this product, and no response.
**DO NOT BUY THIS PRODUCT!!!**

**Comment by boogie** [comment]
They have answered me. They say it is for development purposes, if you want better battery life, I have to upgrade the battery. An upgraded battery won't help a lot.

If you don't want to use this product, but want to learn development, it might work, but I think there are better products for that.

**Comment by lewisxhe** [comment]
Your question has nothing to do with the code, please contact LilyGo if you have a product question

**Comment by boogie** [comment]
@lewisxhe Can you please share **the code** that improves the battery life? I got no answer from you how I can reach the 400uA consumption in sleep mode. It IS a technical issue.
