### ISSUE TITLE
First time flash NON WIFI

### ISSUE THREAD

**Issue by kd4pba** [Xinyuan-LilyGO/LilyGo-T-Wristband#4]
Please provide instructions for first time flash using programmer and NOT WIFI. Provided instructions for device seem to be a mix of confusing instructions.  It appears board needs to be installed in Arduino IDE first.  Also appears first time setup requires flash via USB NOT WIFI.  Very difficult to read into the instructions.

**Comment by lewisxhe** [comment]
The factory is written with non-OTA firmware, so this is a problem, I should like to explain to them, or should I change the readme

**Comment by lewisxhe** [comment]
If there are still problems, please reopen the issue

**Comment by tejaswigowda** [comment]
MPU9250 code always enters OTA mode when enabled.
