### ISSUE TITLE
Could not write

### ISSUE THREAD

**Issue by a9b** [Xinyuan-LilyGO/LilyGo-T-Wristband#5]
I want help
Compilation succeeded, but could not write

This is Error message
```
Arduino：1.8.10 (Mac OS X), ボード："ESP32 Dev Module, Disabled, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 115200, Verbose"
tool.py v2.6
Serial port /dev/cu.SLAB_USBtoUART
Connecting........_____....._____....._____....._____....._____....._____.....____スケッチの書き込み中にエラーが発生しました
_

A fatal error occurred: Failed to connect to ESP32: Timed out waiting for packet header
```

"ESP32 Dev Module" is selected in the procedure of the image below,
Port is "cu.SLAB_USBtoUAR"
https://github.com/Xinyuan-LilyGO/LilyGO-T-Wristband#3-precautions

**Comment by lewisxhe** [comment]
Make sure your FPC terminals are not connected incorrectly

**Comment by lewisxhe** [comment]
If there are still problems, please reopen the issue
